# Monarch SMTP server config file
#
# Service hostname
SERVICE_HOSTNAME: "smtp.gomonar.ch"
# Connect banner
SERVICE_BANNER: "Monarch SMTP server"
# Which port should we bind to?
SERVICE_PORT: 9025
# How many sessions should we accept per IP?
SERVICE_MAX_SESSIONS: 3
# Which domains do we want the SMTPd to receive mail for?
SERVICE_DOMAINS:
  - zzz.theom.nz
  - monarchshells.com
# Do we want SPF on or off?
SERVICE_SPF: 0
# What do we want to say in our EHLO response?
SERVICE_CAPABILITIES:
  - PIPELINING
  - 8BITMIME
  - SMTPUTF8
# Maximum message size (in MB)
SERVICE_MAX_SIZE: 10
# What we say when they say QUIT
SERVICE_GOODBYE: "Goodbye"
# What we say when they don't send EHLO
SERVICE_NO_HELO: "send HELO/EHLO first"
# What we say when they don't say MAIL
SERVICE_NO_MAIL: "send MAIL first"
# What we say when they don't say RCPT
SERVICE_NO_RCPT: "send RCPT first"
# What we say when we've accepted the data
SERVICE_ACCEPTED: "Accepted"
# What we say when they say DATA
SERVICE_DATA_MOTD: "End data with <CR><LF>.<CR><LF>"
# What we say when they say VRFY
SERVICE_VRFY: "Try to send something. No promises though"
# What we say when they say HELP
SERVICE_HELP: "See https://tools.ietf.org/html/rfc5321 for details"
# What we say when they give us the wrong authentication type
SERVICE_UNK_AUTH: "Unrecognized authentication type"
# What we say when they give us an unknown command
SERVICE_UNK_CMD: "command not recognized"
# What we say when they say NOOP or RSET
SERVICE_NOOP: "OK"
# What we say when they say they're done with the data stream
SERVICE_MAIL_QUEUED: "OK: message queued"
# What we say when they try to open more connections than we allow
SERVICE_TOO_MANY_CONNECTIONS: "You have too many open connections"
# What we say when they timeout
SERVICE_TIMEOUT_NOTICE: "Timeout - closing connection"
# What we say when we don't think they are allowed to send mail on behalf of a domain
SERVICE_NO_MATCH: "You aren't on the allowed SPF list for that domain"
# What we say when we don't handle mail for that domain
SERVICE_NO_SUCH_ADDRESS: "I don't handle mail for that domain"
# The maximum amount of time we'll wait (negative 1 second) before flushing the session pool
SERVICE_CLEAR_SESSIONS_TIMER: 301
# The maximum amount of time we'll wait (negative 1 second) for a command before killing them
SERVICE_MAX_TIMEOUT: 21
